{% set version = "0.1.1" %}

package:
  name: soapysdr-module-fcdpp
  version: {{ version }}

source:
  url: https://github.com/pothosware/SoapyFCDPP/archive/refs/tags/soapy-fcdpp-{{ version }}.tar.gz
  sha256: 9625ba28284a2d5b62f7451727d4df65f20ecedbf7769dd9fadd29c50ec251cc

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - alsa-lib  # [linux]
    - libhidapi
    - soapysdr

test:
  commands:
    # verify that libraries get installed
    - test -f $PREFIX/lib/SoapySDR/modules{{ soapysdr }}/libFCDPPSupport.so  # [not win]
    - if not exist %PREFIX%\\Library\\lib\\SoapySDR\\modules{{ soapysdr }}\\FCDPPSupport.dll exit 1  # [win]

    # show info to see if module is detected
    - SoapySDRUtil --info
    - SoapySDRUtil --info | grep FCDPPSupport  # [not win]
    - SoapySDRUtil --info | findstr /l FCDPPSupport  # [win]

    # verify udev rules get installed
    - test -f $PREFIX/lib/udev/rules.d/81-funcube.rules  # [linux]

about:
  home: https://github.com/pothosware/SoapyFCDPP/wiki
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: 'SoapySDR FUNcube Dongle Pro+ Support Module'
  description: >
    This is a SoapySDR driver for the FUNcube dongle pro+. It has been tested it on Raspberry Pi 3 & Orange Pi Zero LTS, typically used for streaming IQ data to GQRX.

    Unlike the gr-osmosdr it's doesn't depend on the gr-fcdproplus block but is standalone depending on libhidapi and ALSA. I believe this makes it a bit more approachable for hacking.

    For Linux users of `soapysdr-module-fcdpp`, you will likely want to link the provided udev rule into your system installation in order for the hardware to have the correct permissions:

        sudo ln -s $CONDA_PREFIX/lib/udev/rules.d/81-funcube.rules /etc/udev/rules.d/
        sudo udevadm control --reload
        sudo udevadm trigger

    You may have to restart for this change to take effect.
  doc_url: https://github.com/pothosware/SoapyFCDPP/wiki
  dev_url: https://github.com/pothosware/SoapyFCDPP

extra:
  recipe-maintainers:
    - ryanvolz
